#!/bin/sh
{
  if [ -z "$EASYNETWORKROOT" ]; then
    echo >&2 "Setting root directory to default: /root/easy-network";
    EASYNETWORKROOT='/root/easy-network';
  fi
} &&
sudo apt-get install -y curl python3 &&
make -C rsa bootstrap &&
make -C vpn bootstrap &&
cat << EOF > .bootstrap.ok &&
export EASYNETWORKROOT='$EASYNETWORKROOT'
source $PWD/rsa/.bootstrap.ok
source $PWD/vpn/.bootstrap.ok
EOF
exit 0
