# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "install-test"
  config.vm.box = "hashicorp/precise64"

  config.vm.hostname = "install-test"
  #config.vm.network :private_network, ip: "10.69.42.2"
  config.vm.provision :file, source: "../../release/easy-network.tgz", destination: "~/easy-network.tgz"
  config.vm.provision :shell, path: "install.sh"
end
