# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :server do |server|
    server.vm.box = "hashicorp/precise64"
    server.vm.network :private_network, ip: "10.69.42.2"
    server.vm.provision :file, source: "../../release/easy-network.tgz", destination: "~/easy-network.tgz"
    server.vm.provision :shell, path: "server.sh"
  end

  config.vm.define :client, autostart: false do |client|
    client.vm.box = "hashicorp/precise64"
    client.vm.network :private_network, ip: "10.69.42.3"
    client.vm.provision :file, source: "../../release/easy-network.tgz", destination: "~/easy-network.tgz"
    client.vm.provision :shell, path: "client.sh"
  end
end
